;;; cli2eli.el --- CLI to Emacs Launch Interface Generator -*- lexical-binding: t; -*-

;; Author: nohzafk
;; Version: 0.2
;; Package-Requires: ((emacs "26.1"))
;; Keywords: tools, convenience
;; URL: https://github.com/nohzafk/cli2eli

;;; Commentary:

;; CLI2ELI generates interactive Emacs commands from JSON configuration files
;; describing CLI tools.  Command templates use ${var} placeholders resolved
;; from built-in context (current file, directory) or declared user inputs
;; (prompts, completions, shell command output).

;;; Code:
(require 'cl-lib)
(require 'json)
(require 'term)

;; ── Customization ──────────────────────────────────────────────

(defgroup cli2eli nil
  "Command line interface to Emacs Launch interface."
  :group 'tools)

(defcustom cli2eli-terminal-backend 'auto
  "Terminal backend for command execution.
When set to `auto', tries eat first, then falls back to term."
  :group 'cli2eli
  :type '(choice (const :tag "Auto-detect (eat > term)" auto)
                 (const :tag "eat" eat)
                 (const :tag "term" term)))

(defcustom cli2eli-default-eat-mode 'semi-char
  "Default input mode for eat terminal."
  :group 'cli2eli
  :type '(choice (const :tag "Semi-char" semi-char)
                 (const :tag "Char" char)
                 (const :tag "Emacs" emacs)
                 (const :tag "Line" line)))

(defcustom cli2eli-output-buffer-name "*CLI2ELI Output*"
  "Buffer name for command output."
  :group 'cli2eli
  :type 'string)

(defcustom cli2eli-output-buffer-display-option
  '(display-buffer-at-bottom . ((window-height . 0.3)))
  "Display options for output buffer."
  :group 'cli2eli
  :type '(choice
          (cons :tag "Display function and alist"
                (function :tag "Display function")
                (alist :key-type symbol :value-type sexp))
          (function :tag "Display function")))

;; ── State ──────────────────────────────────────────────────────

(defvar cli2eli--generated-functions nil
  "List of functions generated by CLI2ELI.")

(defvar cli2eli--current-tool nil
  "Current tool configuration alist.")

(defvar cli2eli--available-backends nil
  "Cached list of available terminal backends.")

;; ── Terminal Backend ───────────────────────────────────────────

(defun cli2eli--detect-backends ()
  "Detect available terminal backends."
  (unless cli2eli--available-backends
    (setq cli2eli--available-backends
          (delq nil
                (list
                 (when (condition-case nil (require 'eat nil t) (error nil)) 'eat)
                 'term))))
  cli2eli--available-backends)

(defun cli2eli--get-backend ()
  "Get the terminal backend to use."
  (cli2eli--detect-backends)
  (if (eq cli2eli-terminal-backend 'auto)
      (car cli2eli--available-backends)
    (if (memq cli2eli-terminal-backend cli2eli--available-backends)
        cli2eli-terminal-backend
      (message "[CLI2ELI] Backend %s not available, falling back to %s"
               cli2eli-terminal-backend (car cli2eli--available-backends))
      (car cli2eli--available-backends))))

;; ── Template Engine ────────────────────────────────────────────

(defconst cli2eli--builtin-vars '("file" "file-relative" "dir")
  "Built-in template variables resolved from Emacs context.")

(defun cli2eli--parse-template-vars (template)
  "Extract ${var} placeholder names from TEMPLATE in order of appearance."
  (let ((vars nil)
        (start 0))
    (while (string-match "\\${\\([^}]+\\)}" template start)
      (let ((var (match-string 1 template)))
        (unless (member var vars)
          (push var vars)))
      (setq start (match-end 0)))
    (nreverse vars)))

(defun cli2eli--builtin-p (var-name)
  "Return non-nil if VAR-NAME is a built-in variable."
  (member var-name cli2eli--builtin-vars))

(defun cli2eli--resolve-builtin (var-name)
  "Resolve built-in variable VAR-NAME to its current value."
  (cond
   ((string= var-name "file")
    (or (buffer-file-name) ""))
   ((string= var-name "file-relative")
    (if (buffer-file-name)
        (file-relative-name (buffer-file-name) (cli2eli--get-working-directory))
      ""))
   ((string= var-name "dir")
    (or default-directory ""))))

(defun cli2eli--expand-template (template values &optional optional-vars)
  "Replace ${var} placeholders in TEMPLATE using VALUES alist.
OPTIONAL-VARS lists variable names where empty values remove the placeholder."
  (let ((result template))
    (dolist (pair values)
      (let* ((var (car pair))
             (val (or (cdr pair) ""))
             (pat (regexp-quote (format "${%s}" var))))
        (if (and (member var optional-vars)
                 (string-empty-p (string-trim val)))
            (setq result (replace-regexp-in-string pat "" result))
          (setq result (replace-regexp-in-string pat val result nil t)))))
    (replace-regexp-in-string "  +" " " (string-trim result))))

;; ── Input Handling ─────────────────────────────────────────────

(defun cli2eli--input-form (var-name spec)
  "Generate an interactive form for input VAR-NAME described by SPEC."
  (let ((type (or (alist-get 'type spec) "prompt"))
        (prompt (or (alist-get 'prompt spec) (capitalize var-name)))
        (choices (append (alist-get 'choices spec) nil))
        (command (alist-get 'command spec)))
    (cond
     (choices
      `(let ((completion-ignore-case t))
         (completing-read
          ,(format "%s: " prompt)
          ',(mapcar (lambda (c)
                      (cond ((eq c t) "true")
                            ((eq c json-false) "false")
                            (t (format "%s" c))))
                    choices)
          nil t)))
     ((string= type "shell")
      `(cli2eli--shell-select ,command ,(format "%s: " prompt)))
     ((string= type "directory")
      `(directory-file-name
        (file-truename
         (expand-file-name
          (read-directory-name ,(format "%s: " prompt))))))
     (t
      `(read-string ,(format "%s: " prompt))))))

(defun cli2eli--generate-interactive-spec (user-vars inputs)
  "Generate interactive spec for USER-VARS using INPUTS alist."
  `(list
    ,@(mapcar
       (lambda (var-name)
         (let ((spec (alist-get (intern var-name) inputs)))
           (cli2eli--input-form var-name spec)))
       user-vars)))

(defun cli2eli--shell-select (command prompt)
  "Run COMMAND, present output lines for selection with PROMPT."
  (let* ((working-directory (cli2eli--get-working-directory))
         (output (cli2eli--execute-local command working-directory))
         (lines (split-string output "\n" t)))
    (completing-read prompt lines nil t)))

;; ── Working Directory ──────────────────────────────────────────

(defun cli2eli--get-working-directory ()
  "Get the working directory for the current tool."
  (let ((cwd (alist-get 'cwd cli2eli--current-tool)))
    (cond
     ((null cwd) (cli2eli--get-default-directory))
     ((string= cwd "") (cli2eli--get-default-directory))
     ((string= cwd "default") (cli2eli--get-default-directory))
     ((string= cwd "git-root")
      (or (locate-dominating-file
           (or (cli2eli--get-default-directory) ".")
           ".git")
          (cli2eli--get-default-directory)))
     (t cwd))))

(defun cli2eli--get-default-directory ()
  "Get the appropriate default directory, handling Docker containers."
  (if (and (file-remote-p default-directory)
           (string-prefix-p "/docker:" default-directory))
      (cli2eli--get-docker-local-folder)
    default-directory))

(defun cli2eli--get-docker-local-folder ()
  "Get the local folder path for a Docker container."
  (let* ((file-name (tramp-dissect-file-name default-directory))
         (container-name (tramp-file-name-host file-name))
         (inspect-command
          (format "docker inspect -f '{{ index .Config.Labels \"devcontainer.local_folder\" }}' %s"
                  container-name))
         (local-folder (string-trim (cli2eli--execute-local inspect-command))))
    (if (string-empty-p local-folder)
        default-directory
      local-folder)))

;; ── Command Execution ──────────────────────────────────────────

(defun cli2eli--get-stdin-content (stdin-source)
  "Get content based on STDIN-SOURCE (\"region\" or \"buffer\")."
  (cond
   ((string= stdin-source "region")
    (if (use-region-p)
        (buffer-substring-no-properties (region-beginning) (region-end))
      (buffer-substring-no-properties (point-min) (point-max))))
   ((string= stdin-source "buffer")
    (buffer-substring-no-properties (point-min) (point-max)))
   (t (error "Unknown stdin source: %s" stdin-source))))

(defun cli2eli--run-command (command)
  "Run COMMAND in a terminal (eat or term)."
  (let* ((output-buffer (get-buffer-create cli2eli-output-buffer-name))
         (cwd (expand-file-name (cli2eli--get-working-directory)))
         (shell (or (alist-get 'shell cli2eli--current-tool) "/bin/bash"))
         (backend (cli2eli--get-backend)))
    (message "[CLI2ELI] Running: %s (cwd: %s, backend: %s)" command cwd backend)
    (when-let ((proc (get-buffer-process output-buffer)))
      (delete-process proc))
    (with-current-buffer output-buffer
      (let ((inhibit-read-only t))
        (pcase backend
          ('eat (eat-mode))
          ('term (term-mode)))
        (compilation-minor-mode)
        (erase-buffer)
        (setq default-directory cwd)
        (insert (format "Working Directory: %s\nRunning: %s\n\n" cwd command))))
    ;; Display buffer before exec so terminal knows window size
    (cli2eli--display-output-buffer output-buffer)
    ;; Run the command
    (with-current-buffer output-buffer
      (let ((exec-args (list output-buffer
                             (format "\"%s\"" command)
                             shell nil
                             (list "-c" (format "cd %s && %s"
                                                (shell-quote-argument cwd)
                                                command)))))
        (pcase backend
          ('eat
           (apply #'eat-exec exec-args)
           (pcase cli2eli-default-eat-mode
             ('semi-char (eat-semi-char-mode))
             ('char (eat-char-mode))
             ('emacs (eat-emacs-mode))
             ('line (eat-line-mode)))
           (add-hook 'window-configuration-change-hook
                     #'cli2eli--eat-handle-window-resize nil t))
          ('term (apply #'term-exec exec-args)))))
    (when-let ((win (get-buffer-window output-buffer)))
      (set-window-point win (point-max)))
    (cli2eli--scroll-to-bottom)))

(defun cli2eli--run-command-to-buffer (command)
  "Run COMMAND synchronously, display output in a read-only buffer."
  (let* ((output-buffer (get-buffer-create cli2eli-output-buffer-name))
         (cwd (expand-file-name (cli2eli--get-working-directory)))
         (shell (or (alist-get 'shell cli2eli--current-tool) "/bin/bash")))
    (message "[CLI2ELI] Running (buffer): %s" command)
    (let ((output (with-temp-buffer
                    (let ((default-directory cwd))
                      (call-process shell nil t nil "-c" command))
                    (buffer-string))))
      (with-current-buffer output-buffer
        (let ((inhibit-read-only t))
          (special-mode)
          (erase-buffer)
          (setq header-line-format (format " Command: %s" command))
          (insert output)))
      (cli2eli--display-output-buffer output-buffer)
      output)))

(defun cli2eli--run-command-with-stdin (command stdin-source)
  "Run COMMAND with stdin from STDIN-SOURCE, display output in buffer."
  (let* ((output-buffer (get-buffer-create cli2eli-output-buffer-name))
         (cwd (expand-file-name (cli2eli--get-working-directory)))
         (shell (or (alist-get 'shell cli2eli--current-tool) "/bin/bash"))
         (stdin-content (cli2eli--get-stdin-content stdin-source)))
    (message "[CLI2ELI] Running with stdin (%s): %s" stdin-source command)
    (when-let ((proc (get-buffer-process output-buffer)))
      (delete-process proc))
    (let ((output (with-temp-buffer
                    (insert stdin-content)
                    (let ((default-directory cwd))
                      (call-process-region (point-min) (point-max)
                                           shell t t nil "-c" command))
                    (buffer-string))))
      (with-current-buffer output-buffer
        (let ((inhibit-read-only t))
          (special-mode)
          (erase-buffer)
          (setq header-line-format (format " Command: %s" command))
          (insert output)))
      (cli2eli--display-output-buffer output-buffer)
      output)))

(defun cli2eli--run-command-replace (command stdin-source)
  "Run COMMAND with stdin from STDIN-SOURCE, replacing source text with output."
  (let* ((cwd (expand-file-name (cli2eli--get-working-directory)))
         (shell (or (alist-get 'shell cli2eli--current-tool) "/bin/bash"))
         (has-region (and (string= stdin-source "region") (use-region-p)))
         (beg (if has-region (region-beginning) (point-min)))
         (end (if has-region (region-end) (point-max))))
    (message "[CLI2ELI] Running (replace): %s" command)
    (let ((default-directory cwd))
      (call-process-region beg end shell t t nil "-c" command))))

(defun cli2eli--display-output-buffer (buffer)
  "Display BUFFER using configured display options and select its window."
  (let ((win (get-buffer-window buffer)))
    (if win (select-window win)
      (display-buffer buffer cli2eli-output-buffer-display-option)
      (setq win (get-buffer-window buffer))
      (when win (select-window win)))))

;; ── Command Definition ─────────────────────────────────────────

(defun cli2eli--value-to-bool (value)
  "Convert VALUE to a boolean."
  (cond
   ((null value) nil)
   ((stringp value) (not (or (string= value "") (string= value "false"))))
   ((eq value 0) nil)
   ((eq value json-false) nil)
   (t value)))

(defun cli2eli--sanitize-function-name (name)
  "Replace invalid characters in NAME for use in function names."
  (replace-regexp-in-string "[^a-zA-Z0-9-]" "-" (downcase name)))

(defun cli2eli--generate-function-name (tool-name cmd-name)
  "Generate function name from TOOL-NAME and CMD-NAME."
  (cli2eli--sanitize-function-name (concat tool-name "-" cmd-name)))

(defun cli2eli--define-command (tool-name cmd)
  "Define an Emacs interactive function for command CMD under TOOL-NAME."
  (let* ((cmd-name (alist-get 'name cmd))
         (cmd-command (alist-get 'command cmd))
         (cmd-desc (or (alist-get 'description cmd) ""))
         (stdin (alist-get 'stdin cmd))
         (output-mode (or (alist-get 'output cmd)
                          (if stdin "buffer" "terminal")))
         (inputs-alist (alist-get 'inputs cmd))
         (template-vars (cli2eli--parse-template-vars cmd-command))
         ;; A var is prompted unless it's a built-in not overridden in inputs
         (user-vars (cl-remove-if
                     (lambda (v)
                       (and (cli2eli--builtin-p v)
                            (not (alist-get (intern v) inputs-alist))))
                     template-vars))
         (builtin-vars (cl-set-difference template-vars user-vars :test #'string=))
         (optional-vars (cl-remove-if-not
                         (lambda (v)
                           (cli2eli--value-to-bool
                            (alist-get 'optional
                                       (alist-get (intern v) inputs-alist))))
                         user-vars))
         (func-name (intern (cli2eli--generate-function-name tool-name cmd-name)))
         (interactive-spec (cli2eli--generate-interactive-spec user-vars inputs-alist)))

    (unless cmd-command
      (error "Command for %s/%s is nil" tool-name cmd-name))

    (message "[CLI2ELI] Generating function: %s" func-name)

    (let ((captured-tool cli2eli--current-tool))
      (fset func-name
            `(lambda (&rest input-values)
               ,cmd-desc
               (interactive (let ((cli2eli--current-tool ',captured-tool))
                              ,interactive-spec))
               (let* ((cli2eli--current-tool ',captured-tool)
                      (builtin-values
                       (mapcar (lambda (v) (cons v (cli2eli--resolve-builtin v)))
                               ',builtin-vars))
                      (user-values
                       (cl-mapcar #'cons ',user-vars input-values))
                      (all-values (append builtin-values user-values))
                      (command (cli2eli--expand-template
                                ,cmd-command all-values ',optional-vars)))
                 ,(cond
                   ((and stdin (string= output-mode "replace"))
                    `(cli2eli--run-command-replace command ,stdin))
                   (stdin
                    `(cli2eli--run-command-with-stdin command ,stdin))
                   ((string= output-mode "buffer")
                    `(cli2eli--run-command-to-buffer command))
                   (t
                    `(cli2eli--run-command command)))))))

    (push func-name cli2eli--generated-functions)))

(defun cli2eli--generate-functions (tool)
  "Generate Emacs functions for all commands in TOOL."
  (let* ((tool-name (alist-get 'tool tool))
         (commands (append (alist-get 'commands tool) nil)))
    (message "[CLI2ELI] Generating functions for tool: %s" tool-name)
    (dolist (cmd commands)
      (cli2eli--define-command tool-name cmd))))

;; ── Tool Loading ───────────────────────────────────────────────

(defun cli2eli--remove-comments-and-schema (json-string)
  "Remove JSON5-style comments and $schema field from JSON-STRING."
  (with-temp-buffer
    (insert json-string)
    (goto-char (point-min))
    (while (re-search-forward "//.*$" nil t)
      (let ((syntax (syntax-ppss)))
        (unless (nth 3 syntax)
          (replace-match ""))))
    (goto-char (point-min))
    (when (re-search-forward "^\\s-*\"\\$schema\".*$" nil t)
      (delete-region (line-beginning-position) (1+ (line-end-position))))
    (goto-char (point-min))
    (while (re-search-forward ",\\s-*\\([])}]\\)" nil t)
      (replace-match "\\1"))
    (buffer-string)))

(defun cli2eli--remove-replaced-functions (tool)
  "Remove functions that will be replaced by TOOL's new configuration."
  (let* ((tool-name (alist-get 'tool tool))
         (commands (append (alist-get 'commands tool) nil)))
    (dolist (cmd commands)
      (let* ((cmd-name (alist-get 'name cmd))
             (func-name (intern (cli2eli--generate-function-name tool-name cmd-name))))
        (when (fboundp func-name)
          (fmakunbound func-name)
          (setq cli2eli--generated-functions
                (delete func-name cli2eli--generated-functions)))))))

;;;###autoload
(defun cli2eli-load-tool (json-file)
  "Load a CLI tool configuration from JSON-FILE."
  (interactive "fSelect JSON configuration file: ")
  (condition-case err
      (let* ((file-path (expand-file-name json-file))
             (json-object-type 'alist)
             (json-array-type 'vector)
             (json-key-type 'symbol)
             (json-string (with-temp-buffer
                            (insert-file-contents file-path)
                            (buffer-string)))
             (cleaned (cli2eli--remove-comments-and-schema json-string))
             (new-tool (json-read-from-string cleaned)))
        (cli2eli--remove-replaced-functions new-tool)
        (setq cli2eli--current-tool new-tool)
        (cli2eli--generate-functions new-tool)
        (message "[CLI2ELI] Loaded tool configuration from %s" json-file))
    (error
     (message "[CLI2ELI] Error loading configuration: %s" (error-message-string err))
     nil)))

;;;###autoload
(defun cli2eli-run ()
  "Interactively select and run a CLI2ELI generated command.
Shows all generated commands with their descriptions as annotations."
  (interactive)
  (unless cli2eli--generated-functions
    (user-error "No CLI2ELI commands loaded"))
  (let* ((candidates
          (mapcar (lambda (sym)
                    (let ((doc (or (documentation sym) "")))
                      (cons (symbol-name sym) doc)))
                  cli2eli--generated-functions))
         (annotate (lambda (cand)
                     (let ((doc (cdr (assoc cand candidates))))
                       (if (string-empty-p doc) ""
                         (concat "  " (propertize doc 'face 'completions-annotations))))))
         (metadata `(metadata (annotation-function . ,annotate)))
         (collection (lambda (str pred action)
                       (if (eq action 'metadata) metadata
                         (complete-with-action action candidates str pred))))
         (choice (completing-read "CLI2ELI: " collection nil t)))
    (call-interactively (intern choice))))

;;;###autoload
(defun cli2eli-remove-generated-functions ()
  "Remove all previously generated CLI2ELI functions."
  (interactive)
  (dolist (func cli2eli--generated-functions)
    (fmakunbound func))
  (setq cli2eli--generated-functions nil))

;; ── Utilities ──────────────────────────────────────────────────

(defun cli2eli--execute-local (command &optional directory)
  "Execute COMMAND on the local host, return output string.
If DIRECTORY is provided, execute in that directory."
  (with-temp-buffer
    (let ((default-directory (or directory default-directory)))
      (call-process-shell-command command nil (current-buffer) nil)
      (buffer-string))))

(defun cli2eli--eat-handle-window-resize ()
  "Handle window resize for eat terminal buffers."
  (when (and (eq major-mode 'eat-mode)
             (bound-and-true-p eat-terminal)
             (get-buffer-process (current-buffer)))
    (let* ((win (get-buffer-window (current-buffer)))
           (width (when win (window-max-chars-per-line win)))
           (height (when win (floor (window-screen-lines win)))))
      (when (and win width height (> width 0) (> height 0))
        (let ((inhibit-read-only t))
          (eat-term-resize eat-terminal width height)
          (eat-term-redisplay eat-terminal))))))

(defun cli2eli--scroll-to-bottom ()
  "Scroll the output buffer to the bottom."
  (let ((win (get-buffer-window (current-buffer))))
    (when win
      (with-selected-window win
        (goto-char (point-max))))))

(provide 'cli2eli)

;;; cli2eli.el ends here
